apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flower.fullname" . }}
  labels:
    {{- include "flower.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flower.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ .Values.basicAuth | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: flower
          image: {{ include "flower.image" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
            - celery
            - -A
            - hc
            - flower
            - --port={{ .Values.port }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          {{- include "flower.env" . | nindent 10 }}
            {{- if or .Values.basicAuth .Values.existingSecret }}
            - name: FLOWER_BASIC_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ include "flower.secretName" . }}
                  key: basic_auth
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
