apiVersion: v1
kind: ConfigMap
metadata:
  name: healthchecks-config
  namespace: healthchecks
data:
  # --- Базовые настройки Django-приложения ---
  ALLOWED_HOSTS: "*"
  SITE_ROOT: "http://localhost:8000"
  DEFAULT_FROM_EMAIL: "noreply@example.com"
  DEBUG: "False"

  # --- Подключение к Postgres (StatefulSet healthchecks-db) ---
  DB: "postgres"
  DB_HOST: "healthchecks-db"
  DB_PORT: "5432"
  DB_NAME: "healthchecks"
  DB_USER: "healthchecks"
