apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthchecks-postgres-pvc
  namespace: healthchecks
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  # selector не обязателен для единственного PV с тем же storageClassName,
  # но явно указываем, чтобы не забиндиться на "чужой" PV, если их станет больше.
  selector:
    matchLabels:
      app: healthchecks-db
