{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "auth.password (or auth.existingSecret) is required when auth.enabled" .Values.auth.password | quote }}
{{- end }}
