apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  # LoadBalancer: снаружи кластера через minikube tunnel (127.0.0.1:6379),
  # внутри кластера — по имени сервиса
  type: {{ .Values.service.type }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
