apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  # Headless: стабильное DNS-имя пода StatefulSet (<fullname>-0.<fullname>-headless)
  clusterIP: None
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
