apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "healthchecks.fullname" . }}
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
data:
  SITE_ROOT: {{ .Values.config.siteRoot | quote }}
  {{- with .Values.config.allowedHosts }}
  ALLOWED_HOSTS: {{ . | quote }}
  {{- end }}
  DEBUG: {{ .Values.config.debug | ternary "True" "False" | quote }}
  DEFAULT_FROM_EMAIL: {{ .Values.config.defaultFromEmail | quote }}
  {{- with .Values.config.secureProxySslHeader }}
  SECURE_PROXY_SSL_HEADER: {{ . | quote }}
  {{- end }}
  {{- with .Values.email.host }}
  EMAIL_HOST: {{ . | quote }}
  EMAIL_PORT: {{ $.Values.email.port | quote }}
  EMAIL_USE_TLS: {{ $.Values.email.useTls | ternary "True" "False" | quote }}
  {{- end }}
  DB: "postgres"
  DB_HOST: {{ include "healthchecks.database.host" . | quote }}
  DB_PORT: {{ include "healthchecks.database.port" . | quote }}
  DB_NAME: {{ include "healthchecks.database.name" . | quote }}
  DB_USER: {{ include "healthchecks.database.user" . | quote }}
