{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "healthchecks.fullname" . }}
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ required "secrets.secretKey is required" .Values.secrets.secretKey | quote }}
{{- end }}
{{- if and .Values.global.s3.enabled (not .Values.global.s3.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "healthchecks.fullname" . }}-s3
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
type: Opaque
stringData:
  access_key: {{ required "secrets.s3AccessKey is required when global.s3.enabled" .Values.secrets.s3AccessKey | quote }}
  secret_key: {{ required "secrets.s3SecretKey is required when global.s3.enabled" .Values.secrets.s3SecretKey | quote }}
{{- end }}
